### ISSUE TITLE
"Command terminated" when saving less files

### ISSUE THREAD

**Issue by bmulholland** [scrooloose/syntastic#1407]
Recently I've started getting a "Command terminated" error every time I save a `.less` file. I dumped the log and here's what I'm seeing:

```
Calling shell to execute: "(lessc --no-color app/assets/stylesheets/contract-ui.css.less > /dev/null) >/v
ar/folders/vz/wfs0t4g55xn0sjpnmf6d9jfc0000gn/T/v6kH6n5/6 2>&1"
Command terminated
```

I tried running it myself, and it seems that the error is happening because the folder doesn't exist:

`zsh: no such file or directory: /var/folders/vz/wfs0t4g55xn0sjpnmf6d9jfc0000gn/T/v6kH6n5/6`

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 1, run the checker, run `:mes`, and post the output.

**Comment by bmulholland** [comment]
```
syntastic: 7.358630: &shell = '/usr/local/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape
= ''
syntastic: 7.358873: UpdateErrors (auto): default checkers
syntastic: 7.359190: CacheErrors: default checkers
syntastic: 7.359808: g:syntastic_aggregate_errors = 0
syntastic: 7.359990: getcwd() = '/Users/bmulholland/dev/contractually'
syntastic: 7.368397: CacheErrors: Invoking checker: less/lessc
syntastic: 7.369113: SyntasticMake: called with options: {'postprocess': ['guards'], 'errorformat': '%m in %f on line %l\, column %c:,%m in %f:%l:%c,%-G%.%#', 'defaults': {'bufnr': 1, 'text': 'Syntax error'}, '
makeprg': 'lessc --no-color app/assets/stylesheets/contract-ui.css.less > /dev/null'}
Command terminated
syntastic: 11.069768: getLocList: checker less/lessc returned -1   
```

**Comment by lcd047** [comment]
Please open your test file, run `:SyntasticInfo`, and post the output.  Then run this and post the output:
```
:echo system('lessc --no-color app/assets/stylesheets/contract-ui.css.less > /dev/null')
```

**Comment by bmulholland** [comment]
```
Syntastic version: 3.6.0-80 (Vim 704, Darwin)
Info for filetype: less
Global mode: active
Filetype less is active
The current file will be checked automatically
Available checker: lessc
Currently enabled checker: lessc
```

```
Command terminated
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/therubyracer-0.12.2/lib/v8/init.bundle: [BUG] Segmentation fault
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0024 p:-17578366478048 s:0113 e:000112 TOP    [FINISH]
c:0023 p:---- s:0111 e:000110 CFUNC  :require
c:0022 p:0115 s:0107 e:000106 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0021 p:0023 s:0097 e:000096 TOP    /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/therubyracer-0.12.2/lib/v8.rb:4 [FINISH]
c:0020 p:---- s:0095 e:000094 CFUNC  :require
c:0019 p:0073 s:0091 e:000090 BLOCK  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135
c:0018 p:0442 s:0088 e:000087 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144
c:0017 p:0022 s:0078 e:000077 TOP    /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less/java_script/v8_context.rb:2 [FINISH]
c:0016 p:---- s:0075 e:000074 CFUNC  :require
c:0015 p:0115 s:0071 e:000070 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0014 p:0042 s:0061 e:000060 METHOD /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less/java_script.rb:9
c:0013 p:0020 s:0058 e:000057 METHOD /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less/java_script.rb:17
c:0012 p:0015 s:0055 e:000054 METHOD /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less/loader.rb:13 [FINISH]
c:0011 p:---- s:0050 e:000049 CFUNC  :new
c:0010 p:0030 s:0047 e:000046 CLASS  /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less.rb:14
c:0009 p:0057 s:0045 e:000044 TOP    /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less.rb:9 [FINISH]
c:0008 p:---- s:0043 e:000042 CFUNC  :require
c:0007 p:0115 s:0039 e:000038 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0006 p:0007 s:0029 e:000028 TOP    /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/bin/lessc:3 [FINISH]
c:0005 p:---- s:0019 e:000018 CFUNC  :load
c:0004 p:0134 s:0015 E:001948 EVAL   /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/bin/lessc:23 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :eval
c:0002 p:0118 s:0005 E:001660 EVAL   /Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/bin/ruby_executable_hooks:15 [FINISH]
c:0001 p:0000 s:0002 E:000158 TOP    [FINISH]

/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/bin/ruby_executable_hooks:15:in `<main>'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/bin/ruby_executable_hooks:15:in `eval'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/bin/lessc:23:in `<main>'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/bin/lessc:23:in `load'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/bin/lessc:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less.rb:9:in `<top (required)>'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less.rb:14:in `<module:Less>'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less.rb:14:in `new'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less/loader.rb:13:in `initialize'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less/java_script.rb:17:in `context_wrapper'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less/java_script.rb:9:in `default_context_wrapper'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/less-2.6.0/lib/less/java_script/v8_context.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
/Users/bmulholland/.rvm/gems/ruby-2.2.2@contractually/gems/therubyracer-0.12.2/lib/v8.rb:4:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```


I thought that this was different from https://github.com/scrooloose/syntastic/issues/1310 but the more I look into it, the more they look the same. I get the same crash with `echo system('lessc --version')`. Changing my shell to `sh` makes the crash go away, and things start working again. What's weird is that manually running the command in zsh works.

Seems like this might be outside of syntastic, but do you have any suggestions on things I can investigate? Google only turns up syntastic-related results.

**Comment by lcd047** [comment]
That it's outside syntastic was actually apparent from the very beginning, but you wouldn't have believed me without the above dance. :)

The problem is likely to be either in your zsh settings, but it's hard to debug because Vim's `system()` is a spaghetti monster.  There are a few things you could try, but none of them is likely to give you a definitive answer.  You might try looking at `:echo system('set')` and compare it with what you get in the shell.  Or you might just run a debugger instead of lessc.  Or try to strace / ktrace / truss the lessc process and see why it crashes.
