### ISSUE TITLE
checker rubocop not available

### ISSUE THREAD

**Issue by joshpfosi** [scrooloose/syntastic#1433]
I've found previous issues about this but I updated my Ruby version and so now `rubocop --version` yields

```
0.31.0
```

but `syntastic` still cannot find it. The only line in my `.vimrc` pertinent is: `let g:syntastic_ruby_checkers=['rubocop', 'mri']`.

What am I missing?

**Comment by lcd047** [comment]
Please open a Ruby file, set `g:syntastic_debug` to 33, run `:SyntasticInfo`, and post the output.

**Comment by joshpfosi** [comment]
Syntastic version: 3.5.0-72
Info for filetype: ruby
Global mode: active
Filetype ruby is active
The current file will be checked automatically
syntastic: 20.486434: ruby/rubocop: rubocop version = [0, 31, 0]
Available checkers: mri rubocop
Currently enabled checkers: rubocop mri

**Comment by lcd047** [comment]
Which shows that rubocop is available to syntastic just fine.

So: what did you do, wha did you expect to happen, and what happened instead?

**Comment by joshpfosi** [comment]
Right, so I ran `rubocop` from the command line, determining that many of my files had issues. I wanted syntastic to work as it does with my other checkers and indicate improper lines on Vim's sidebar. So I opened a misbehaving file, save the file, expecting the sidebar to be updated and nothing occurred. Upon running `SyntasticCheck` it yielded the `rubocop unavailable` message.

**Comment by lcd047** [comment]
Please open one of the files with issues, set `g:syntastic_debug` to 3, run `:SyntasticCheck rubocop`, then run `:mes` and post the output.

**Comment by joshpfosi** [comment]
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"spec/controllers/information_modules_controller_spec.rb" 88L, 3074C
syntastic: 15.969023: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote =
'', &shellxescape = ''
syntastic: 15.969304: UpdateErrors: rubocop
syntastic: 15.969654: CacheErrors: rubocop
syntastic: 15.970410: g:syntastic_aggregate_errors = 0
syntastic: 15.970623: getcwd() = /Users/joshpfosi/shearwater/rails
syntastic: 17.232039: CacheErrors: Invoking checker: ruby/rubocop
syntastic: 17.233675: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%f:%l:%c: %t: %m', 'makeprg': 'rubocop --format emacs --silent spec/controllers/informati
on_modules_controller_spec.rb'}
syntastic: 17.943844: checker output: ['invalid option: --silent', '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/lib/rubocop/options.rb:68:in `parse''', '/Users/joshpfosi/
.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/lib/rubocop/cli.rb:21:in `run''', '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/bin/rubocop:13:in `block in <top (required)>''', '
/Users/joshpfosi/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime''', '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/bin/rubocop:12:in `<top (required)>'
'', '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/bin/rubocop:23:in `load''', '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/bin/rubocop:23:in `<main>''', '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/bin/r
uby_executable_hooks:15:in `eval''', '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>''', '']
syntastic: 17.944954: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'invalid option: --silent'}, {'lnum': 0, 'bufn
r': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/lib/rubocop/options.rb:68:in `parse'''},
 {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/lib/rubocop/cli.rb:21:
in `run'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/bin/ruboco
p:13:in `block in <top (required)>'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/Users/joshpfosi/.rvm/rubies/ruby-2.1.6/l
ib/ruby/2.1.0/benchmark.rb:294:in `realtime'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/Users/joshpfosi/.rvm/gems/ruby-
2.1.6/gems/rubocop-0.31.0/bin/rubocop:12:in `<top (required)>'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/Users/joshpfo
si/.rvm/gems/ruby-2.1.6/bin/rubocop:23:in `load'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/Users/joshpfosi/.rvm/gems/r
uby-2.1.6/bin/rubocop:23:in `<main>'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/bi
n/ruby_executable_hooks:15:in `eval'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/bi
n/ruby_executable_hooks:15:in `<main>'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 17.946367: getLocList: checker ruby/rubocop returned 1
syntastic: 17.946481: ruby/rubocop raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': 'invalid option: --s
ilent'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/gems/rubocop-
0.31.0/lib/rubocop/options.rb:68:in `parse'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': '/Users/joshp
fosi/.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/lib/rubocop/cli.rb:21:in `run'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype
': 'Style', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/bin/rubocop:13:in `block in <top (required)>'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0
, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': '/Users/joshpfosi/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'''}, {'lnum': 0, 'bufnr': 0, '
col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/gems/rubocop-0.31.0/bin/rubocop:12:in `<top (re
quired)>'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/bin/rubo
cop:23:in `load'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': '/Users/joshpfosi/.rvm/gems/ruby-2.1.6/b
in/rubocop:23:in `<main>'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': '/Users/joshpfosi/.rvm/gems/rub
y-2.1.6/bin/ruby_executable_hooks:15:in `eval'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': '/Users/jo
shpfosi/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Sty
le', 'text': ''}]
syntastic: 17.947216: quiet_messages filter: {}
syntastic: 17.947541: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}   
```

**Comment by lcd047** [comment]
> 'invalid option: --silent'

Right: please upgrade syntastic to the current master HEAD, and try again.

**Comment by joshpfosi** [comment]
Ok I believe I am to date. Just ran `:SyntasticCheck` which did not error but also did not populate the sidebar.

Rerunning `:mes` yields:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"spec/controllers/information_modules_controller_spec.rb" 88L, 3074C
"spec/controllers/information_modules_controller_spec.rb" 88L, 3074C written
"spec/controllers/information_modules_controller_spec.rb" 88L, 3074C written
syntastic: 46.646549: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote =
'', &shellxescape = ''
syntastic: 46.647257: UpdateErrors: default checkers
syntastic: 46.648189: CacheErrors: default checkers
syntastic: 46.649942: g:syntastic_aggregate_errors = 0
syntastic: 46.650400: getcwd() = '/Users/joshpfosi/shearwater/rails'
syntastic: 46.651309: CacheErrors: Invoking checker: ruby/rubocop
syntastic: 46.652807: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%f:%l:%c: %t: %m', 'makeprg': 'rubocop --format emacs spec/controllers/information_module
s_controller_spec.rb'}
syntastic: 47.588612: checker output: ['']
syntastic: 47.589246: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 47.589630: getLocList: checker ruby/rubocop returned 0
syntastic: 47.589819: ruby/rubocop raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': ''}]
syntastic: 47.590086: quiet_messages filter: {}
syntastic: 47.590473: CacheErrors: Invoking checker: ruby/mri
syntastic: 47.591257: SyntasticMake: called with options: {'errorformat': '%-G%\m%.%#warning: %\%%(possibly %\)%\?useless use of == in void context,%-G%\%.%\%.%\%.%.%#,%-GSyntax OK,%E%
f:%l: syntax error\, %m,%Z%p^,%W%f:%l: warning: %m,%Z%p^,%W%f:%l: %m,%-C%.%#', 'makeprg': 'ruby -w -T1 -c spec/controllers/information_modules_controller_spec.rb', 'env': {'RUBYOPT': '
'}}
syntastic: 47.667523: checker output: ['Syntax OK', '']
syntastic: 47.667925: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 47.668104: getLocList: checker ruby/mri returned 0
syntastic: 47.668212: ruby/mri raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 47.668367: quiet_messages filter: {}
syntastic: 47.668632: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
syntastic: 50.829766: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote =
'', &shellxescape = ''
syntastic: 50.830051: UpdateErrors: rubocop
syntastic: 50.830398: CacheErrors: rubocop
syntastic: 50.831191: g:syntastic_aggregate_errors = 0
syntastic: 50.831433: getcwd() = '/Users/joshpfosi/shearwater/rails'
syntastic: 50.831987: CacheErrors: Invoking checker: ruby/rubocop
syntastic: 50.833310: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%f:%l:%c: %t: %m', 'makeprg': 'rubocop --format emacs spec/controllers/information_module
s_controller_spec.rb'}
syntastic: 51.724291: checker output: ['']
syntastic: 51.724874: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 51.725250: getLocList: checker ruby/rubocop returned 0
syntastic: 51.725431: ruby/rubocop raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': ''}]
syntastic: 51.725702: quiet_messages filter: {}
syntastic: 51.726095: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}  
```

**Comment by lcd047** [comment]
> checker output: ['']

This means rubocop didn't find any errors...

**Comment by joshpfosi** [comment]
Yep, sorry my .rubocop.yml was killing them. Upgrading fixed it :) Thanks!
