### ISSUE TITLE
.eslintrc with extends

### ISSUE THREAD

**Issue by njj** [scrooloose/syntastic#1552]
Hello,  I've recently found that my vim will not report errors if I use the extends feature of eslint.  If I write my own rules, everything works as expected but something like:

```
{
  "extends": "standard",
  "parser": "babel-eslint",
  "env": {
    "node": true,
    "es6": true,
    "browser": true
  },
  "ecmaFeatures": {
    "modules": true
  }
}
```

Seems to prevent Syntastic from reporting anything.  By removing the extends line, everything works fine.

Any ideas?

**Comment by lcd047** [comment]
Please open your test file, run `:SyntasticInfo`, and post the output.  Then set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output again.

**Comment by njj** [comment]
SyntasticInfo
```
Syntastic version: 3.6.0-146 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: eslint flow jsxhint standard
Currently enabled checker: eslint
```

mes
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"src/exporter.js" 168L, 3559C
Syntastic version: 3.6.0-146 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: eslint flow jsxhint standard
Currently enabled checker: eslint
Pattern not found: syntastic_debug
```

@lcd047

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, that is, run
```vim
:let g:syntastic_debug=3
```
on Vim's command line, thenm run the checker, that is, run
```vim
:SyntasticCheck eslint
```
and then run `:mes` and post the output.

**Comment by njj** [comment]
```
syntastic: 17.503978: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &she
lltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 17.504532: UpdateErrors: eslint
syntastic: 17.504815: CacheErrors: eslint
syntastic: 17.505462: g:syntastic_aggregate_errors = 0
syntastic: 17.505660: getcwd() = '/Users/nickjustice/Development/Sartre'
syntastic: 17.506050: CacheErrors: Invoking checker: javascript/eslint
syntastic: 17.506708: SyntasticMake: called with options: {'postprocess': ['guards'], 'errorformat': '%E%f: line %l\, col %c\, Error - %m,%W%f: line %l\, co
l %c\, Warning - %m', 'makeprg': 'eslint -f compact src/exporter.js'}
syntastic: 17.936608: checker output: ['/usr/local/lib/node_modules/eslint/lib/config.js:171', '                    throw e;', '                          ^'
, 'Error: Cannot find module ''eslint-config-standard''', 'Referenced from: /Users/nickjustice/Development/Sartre/.eslintrc', '    at Function.Module._resol
veFilename (module.js:336:15)', '    at Function.Module._load (module.js:278:25)', '    at Module.require (module.js:365:17)', '    at require (module.js:38
4:17)', '    at readConfigFromFile (/usr/local/lib/node_modules/eslint/lib/config.js:113:44)', '    at loadConfig (/usr/local/lib/node_modules/eslint/lib/co
nfig.js:134:22)', '    at /usr/local/lib/node_modules/eslint/lib/config.js:165:46', '    at Array.reduceRight (native)', '    at loadConfig (/usr/local/lib/
node_modules/eslint/lib/config.js:149:36)', '    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:273:23)', '']
syntastic: 17.937495: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/usr/local/lib/no
de_modules/eslint/lib/config.js:171'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '
      throw e;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '                          ^'}, {'ln
um': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Error: Cannot find module ''eslint-config-standard'''}, {
'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Referenced from: /Users/nickjustice/Development/Sartre
/.eslintrc'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Function.Module._resolveFilename
 (module.js:336:15)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Function.Module._load (
module.js:278:25)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Module.require (module.js
:365:17)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at require (module.js:384:17)'}, {'ln
um': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at readConfigFromFile (/usr/local/lib/node_modules/es
lint/lib/config.js:113:44)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at loadConfig (/usr
/local/lib/node_modules/eslint/lib/config.js:134:22)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text'
: '    at /usr/local/lib/node_modules/eslint/lib/config.js:165:46'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern
': '', 'text': '    at Array.reduceRight (native)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:149:36)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': ''
, 'pattern': '', 'text': '    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:273:23)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, '
vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 17.938927: postprocess: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/usr/local/lib/no
de_modules/eslint/lib/config.js:171'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '
      throw e;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '                          ^'}, {'ln
um': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Error: Cannot find module ''eslint-config-standard'''}, {
'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Referenced from: /Users/nickjustice/Development/Sartre
/.eslintrc'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Function.Module._resolveFilename
 (module.js:336:15)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Function.Module._load (
module.js:278:25)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Module.require (module.js
:365:17)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at require (module.js:384:17)'}, {'ln
um': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at readConfigFromFile (/usr/local/lib/node_modules/es
lint/lib/config.js:113:44)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at loadConfig (/usr
/local/lib/node_modules/eslint/lib/config.js:134:22)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text'
: '    at /usr/local/lib/node_modules/eslint/lib/config.js:165:46'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern
': '', 'text': '    at Array.reduceRight (native)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:149:36)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': ''
, 'pattern': '', 'text': '    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:273:23)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, '
vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 17.940190: getLocList: checker javascript/eslint returned 1
syntastic: 17.940330: javascript/eslint raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/usr/lo
cal/lib/node_modules/eslint/lib/config.js:171'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '
                throw e;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '
 ^'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Error: Cannot find module ''eslint-config-stand
ard'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Referenced from: /Users/nickjustice/Developm
ent/Sartre/.eslintrc'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Function.Module._resol
veFilename (module.js:336:15)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Function.Modu
le._load (module.js:278:25)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Module.require
(module.js:365:17)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at require (module.js:384:1
7)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at readConfigFromFile (/usr/local/lib/node_
modules/eslint/lib/config.js:113:44)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at loadCo
nfig (/usr/local/lib/node_modules/eslint/lib/config.js:134:22)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern':
'', 'text': '    at /usr/local/lib/node_modules/eslint/lib/config.js:165:46'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': ''
, 'pattern': '', 'text': '    at Array.reduceRight (native)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '',
 'text': '    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:149:36)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1,
'type': '', 'pattern': '', 'text': '    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:273:23)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
```

**Comment by lcd047** [comment]
This is your problem, your `eslint` crashes:

> 'Error: Cannot find module ''eslint-config-standard'''

You can probably reproduce the problem by running `eslint -f compact src/exporter.js` in a terminal.  Fix it, and syntastic should work fine.  Sadly, syntastic can't detect the crash and warn you about it, because `eslint` returns exit code 1 both when it finds errors in the files to be checked, and when it runs into configuration problems. _shrug_

**Comment by njj** [comment]
@lcd047 thanks!

**Comment by colbycheeze** [comment]
How did you fix this? I have the same problem. My syntastic is also looking in `user/local/lib/node_modules` which is incorrect. It should be looking within the local project node_modules...but I don't know how to fix that?

**Comment by njj** [comment]
@colbycheeze I think I ended up installing `eslint-config-standard` globally in this case.

**Comment by colbycheeze** [comment]
Ah, that seems like kind of a hack. Would be awesome to know if there is a way to point it to the local installs =/

**Comment by njj** [comment]
@colbycheeze I'm user @lcd047 could help.

**Comment by lcd047** [comment]
Please see #1692 for a better approach to running local modules.
