### ISSUE TITLE
getting new error parsing eslint output

### ISSUE THREAD

**Issue by davidosomething** [scrooloose/syntastic#1560]
updated to latest today

getting this err for eslint

```
syntastic: error: checker output:
module.js:338
    throw err;
          ^
Error: Cannot find module 'esrecurse'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/david/.nvm/versions/node/v0.12.5/lib/node_modules/eslint/node_modules/escope/lib/referencer.js:39:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
syntastic: error: checker javascript/eslint: can't parse version string (abnormal termination?)
```

running latest eslint and npm 3.3.3

**Comment by lcd047** [comment]
> `syntastic: error: checker output:`

Your brand new `eslint` crashes, with the output above.  Fix the crash, and syntastic should be fine.
