### ISSUE TITLE
scss/scss_lint: unrecognized error format suddenly appearing and linting doesn't work

### ISSUE THREAD

**Issue by benjamincharity** [scrooloose/syntastic#1733]
Syntastic no longer runs the SCSS checker and simply outputs this message: 

> Error message: `syntastic: warning: checker scss/scss_lint: unrecognized error format`

I did recently update my installation of Vim so that may have some effect. I thought it may have something to do with the checker itself so I reinstalled the scss_lint gem. (I couldn't install to Apple's ruby so I installed rbenv and ruby 2.2.1 and then installed the gem).

Any help or ideas would be greatly appreciated!

### Steps to reproduce

- Run the SCSS checker on a SCSS file.

### Setup

- Vim: `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 17 2016 13:06:45) (compiled by Homebrew)`
- Syntastic: `Syntastic version: 3.7.0-102 (Vim 704, Darwin)`
- SCSS_Lint: `scss_lint (0.47.1)` (using rbenv and ruby 2.2.1)

### Output of Syntastic Debug

```
"src/app/components/modals/confirm/confirm.scss" 50L, 817C written
syntastic: 3799.022090: &shell = '/bin/sh' (!), &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 3799.022823: UpdateErrors (auto): default checkers
syntastic: 3799.023254: CacheErrors: default checkers
syntastic: 3799.024164: g:syntastic_aggregate_errors = 0
syntastic: 3799.024402: getcwd() = '/Users/bc/Code/moment/moment-client'
syntastic: 3799.024855: CacheErrors: Invoking checker: scss/scss_lint
syntastic: 3799.025457: SyntasticMake: called with options: {'postprocess': ['guards'], 'preprocess': 'scss_lint', 'errorformat': '%f:%t:%l:%c:%n:%m', 'makeprg': 'scss-lint -f JSON src/app/components/modals/confirm/confirm.scss', 'returns': [0, 1, 2, 65, 66]}
syntastic: 3799.158633: checker output: ['/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:313:in `to_specs'': Could not find ''scss_lint'' (>= 0) among 164 total gem(s) (Gem::LoadError)', 'Checked in ''GEM_PATH=/Users/bc/.gem/ruby/2.0.0:/Library/Ruby/Gems/2.0.0:/System/Libra
ry/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0'', execute `gem env` for more information', '^Ifrom /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:322:in `to_spec''', '^Ifrom /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:58:in `gem''', '^Ifrom /
usr/local/bin/scss-lint:22:in `<main>''', '']
syntastic: warning: checker scss/scss_lint: unrecognized error format
syntastic: 3799.159097: preprocess: []
syntastic: 3799.159225: raw loclist: []
syntastic: 3799.159344: postprocess: []
syntastic: 3799.159475: getLocList: checker scss/scss_lint returned 1
syntastic: 3799.159552: scss/scss_lint raw: []
syntastic: 3799.159644: quiet_messages filter: {}
syntastic: 3799.159850: aggregated: {'_sorted': 0, '_name': '', '_owner': 17, '_columns': 1, '_rawLoclist': []}
```

### Output of Debug :mes

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 17 2016 13:06:45)
Syntastic version: 3.7.0-102 (Vim 704, Darwin)
Info for filetype: scss
Global mode: active
Filetype scss is active
The current file will be checked automatically
Available checkers: sass scss_lint
Currently enabled checker: scss_lint
1 change; before #17  1 seconds ago
"src/app/components/modals/confirm/confirm.scss" 50L, 817C written
syntastic: 3799.022090: &shell = '/bin/sh' (!), &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 3799.022823: UpdateErrors (auto): default checkers
syntastic: 3799.023254: CacheErrors: default checkers
syntastic: 3799.024164: g:syntastic_aggregate_errors = 0
syntastic: 3799.024402: getcwd() = '/Users/bc/Code/moment/moment-client'
syntastic: 3799.024855: CacheErrors: Invoking checker: scss/scss_lint
syntastic: 3799.025457: SyntasticMake: called with options: {'postprocess': ['guards'], 'preprocess': 'scss_lint', 'errorformat': '%f:%t:%l:%c:%n:%m', 'makeprg': 'scss-lint -f JSON src/app/components/modals/confirm/confirm.scss', 'returns': [0, 1, 2, 65, 66]}
syntastic: 3799.158633: checker output: ['/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:313:in `to_specs'': Could not find ''scss_lint'' (>= 0) among 164 total gem(s) (Gem::LoadError)', 'Checked in ''GEM_PATH=/Users/bc/.gem/ruby/2.0.0:/Library/Ruby/Gems/2.0.0:/System/Libra
ry/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0'', execute `gem env` for more information', '^Ifrom /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:322:in `to_spec''', '^Ifrom /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:58:in `gem''', '^Ifrom /
usr/local/bin/scss-lint:22:in `<main>''', '']
syntastic: warning: checker scss/scss_lint: unrecognized error format
syntastic: 3799.159097: preprocess: []
syntastic: 3799.159225: raw loclist: []
syntastic: 3799.159344: postprocess: []
syntastic: 3799.159475: getLocList: checker scss/scss_lint returned 1
syntastic: 3799.159552: scss/scss_lint raw: []
syntastic: 3799.159644: quiet_messages filter: {}
syntastic: 3799.159850: aggregated: {'_sorted': 0, '_name': '', '_owner': 17, '_columns': 1, '_rawLoclist': []}
E481: No range allowed
"src/app/components/modals/confirm/confirm.scss" 50L, 817C written
syntastic: 3939.110143: &shell = '/bin/sh' (!), &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 3939.110688: UpdateErrors (auto): default checkers
syntastic: 3939.111113: CacheErrors: default checkers
syntastic: 3939.112017: g:syntastic_aggregate_errors = 0
syntastic: 3939.112255: getcwd() = '/Users/bc/Code/moment/moment-client'
syntastic: 3939.112705: CacheErrors: Invoking checker: scss/scss_lint
syntastic: 3939.113316: SyntasticMake: called with options: {'postprocess': ['guards'], 'preprocess': 'scss_lint', 'errorformat': '%f:%t:%l:%c:%n:%m', 'makeprg': 'scss-lint -f JSON src/app/components/modals/confirm/confirm.scss', 'returns': [0, 1, 2, 65, 66]}
syntastic: 3939.251107: checker output: ['/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:313:in `to_specs'': Could not find ''scss_lint'' (>= 0) among 164 total gem(s) (Gem::LoadError)', 'Checked in ''GEM_PATH=/Users/bc/.gem/ruby/2.0.0:/Library/Ruby/Gems/2.0.0:/System/Libra
ry/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0'', execute `gem env` for more information', '^Ifrom /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:322:in `to_spec''', '^Ifrom /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:58:in `gem''', '^Ifrom /
usr/local/bin/scss-lint:22:in `<main>''', '']
syntastic: warning: checker scss/scss_lint: unrecognized error format
syntastic: 3939.251608: preprocess: []
syntastic: 3939.251750: raw loclist: []
syntastic: 3939.251868: postprocess: []
syntastic: 3939.252017: getLocList: checker scss/scss_lint returned 1
syntastic: 3939.252099: scss/scss_lint raw: []
syntastic: 3939.252190: quiet_messages filter: {}
syntastic: 3939.252399: aggregated: {'_sorted': 0, '_name': '', '_owner': 17, '_columns': 1, '_rawLoclist': []}  
```

**Comment by benjamincharity** [comment]
After a restart it seems to be working now...Sorry I have nothing useful to offer anyone else who stumbles upon this. Closing since it is resolved (at least for now).

Thanks for improving my daily workflow!

**Comment by ddaza** [comment]
I had the same problem. It seems that the Ruby1.9 version of scss_lint was causing the error. I tried installing Ruby2.2 and the scss_lint gem and the problem went away. 

Hope this helps someone.

**Comment by ain** [comment]
Calling for reopen. Experiencing the same error with latest scss_lint `0.49.0`, ruby `2.3.1` and aa2a09110956e46652a9cb247ec24a57797066fd of syntastic.

**Comment by lcd047** [comment]
@ain The OP's problem had nothing to do with syntastic:

> syntastic: 3939.251107: checker output: ['/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:313:in `to_specs'': Could not find ''scss_lint'' (>= 0) among 164 total gem(s) (Gem::LoadError)'

If you have the same problem then you should consider fixing your installation of `SCSS-Lint`.  If you have a different problem then please open a new issue, and explain what you did, what did you expect to happen, and what happened instead.

**Comment by ain** [comment]
Thanks for prompt feedback @lcd047. I'll do some research in the evening, it could also be caused by invalid Shell for tmux/Vim (using gemfiles from RVM).

**Comment by ain** [comment]
Just retested and unfortunately no luck. Reported #1843.
