### ISSUE TITLE
"unrecognized error format" thrown on SCSS save

### ISSUE THREAD

**Issue by ain** [scrooloose/syntastic#1843]
__How to reproduce__:

1. Install scss_lint:

        gem install scss_lint

2. Open SCSS file in Vim
3. Save it

__What happens__: warning is thrown:

```
syntastic: warning: checker scss/scss_lint: unrecognized error format  
``` 

__What should happen__: warning should not have been thrown.

Platform: scss_lint `0.49.0`, ruby `2.3.1` and aa2a09110956e46652a9cb247ec24a57797066fd of syntastic

**Comment by lcd047** [comment]
Please post a test file that can be used to reproduce the problem.

**Comment by ain** [comment]
It happens with __any SCSS file__. 

I tested further. Problem relates to Ruby `2.3.1`.  The warning is not there when `scss_lint` gets run on older rubies, e.g. `2.1.5` or `2.2.4`.

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run `:SyntasticCheck scss_lint`, run `:mes`, and post the output.

**Comment by ain** [comment]
Looks like a `scss_lint` problem to me:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>                                                                                                                                                                 
"_sass/base/_body.scss" 5L, 71C                                                                                                                                                                                    
syntastic: 8.326664: &shell = '/opt/local/bin/bash' (!), &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxesc
ape = ''                                                                                                                                                                                                           
syntastic: 8.327144: UpdateErrors: scss_lint                                                                                                                                                                       
syntastic: 8.327419: CacheErrors: scss_lint                                                                                                                                                                        
syntastic: 8.328007: g:syntastic_aggregate_errors = 0                                                                                                                                                              
syntastic: 8.328268: getcwd() = '/Users/ain/Documents/projects/tekkie'                                                                                                                                             
syntastic: 8.349347: system: command run in 0.011354s                                                                                                                                                              
syntastic: 8.820330: system: command run in 0.451474s                                                                                                                                                              
syntastic: 8.820740: CacheErrors: Invoking checker: scss/scss_lint                                                                                                                                                 
syntastic: 8.821543: SyntasticMake: called with options: {'postprocess': ['guards'], 'preprocess': 'scss_lint', 'errorformat': '%f:%t:%l:%c:%n:%m', 'makeprg': 'scss-lint -f JSON _sass/base/_body.scss', 'returns'
: [0, 1, 2, 65, 66]}                                                                                                                                                                                               
syntastic: 9.134846: system: command run in 0.312920s                                                                                                                                                              
syntastic: 9.135008: checker output: ['/Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing'': undefined method `this'' for #<Gem::Specification:0x3fed0d022b98 scss_
lint-0.49.0> (NoMethodError)', '^Ifrom /Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path''', '^Ifrom /Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/ru
bygems/core_ext/kernel_require.rb:64:in `require''', '^Ifrom /Users/ain/.rvm/gems/ruby-2.3.1/gems/scss_lint-0.49.0/bin/scss-lint:3:in `<top (required)>''', '^Ifrom /Users/ain/.rvm/gems/ruby-2.3.1/bin/scss-lint:2
3:in `load''', '^Ifrom /Users/ain/.rvm/gems/ruby-2.3.1/bin/scss-lint:23:in `<main>''', '^Ifrom /Users/ain/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval''', '^Ifrom /Users/ain/.rvm/gems/ruby-2.3.1/bi
n/ruby_executable_hooks:15:in `<main>''', '']                                                                                                                                                                      
syntastic: warning: checker scss/scss_lint: unrecognized error format                                                                                                                                              
syntastic: 9.138289: preprocess: []                                                                                                                                                                                
syntastic: 9.138509: raw loclist: []                                                                                                                                                                               
syntastic: 9.139247: postprocess: []                                                                                                                                                                               
syntastic: 9.139407: getLocList: checker scss/scss_lint returned 1                                                                                                                                                 
syntastic: 9.139526: scss/scss_lint raw: []                                                                                                                                                                        
syntastic: 9.139689: quiet_messages filter: {}                                                                                                                                                                     
syntastic: 9.139812: getLocList: checker scss/scss_lint run in 0.318883s                                                                                                                                           
syntastic: 9.140086: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}   
```

**Comment by lcd047** [comment]
> syntastic: 9.135008: checker output: ['/Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing'': undefined method `this'' for #<Gem::Specification:0x3fed0d022b98 scss_lint-0.49.0> (NoMethodError)'...

Please fix your installation and try again.  Feel free to re-open this if / when you can actually point to a problem related to syntastic.

**Comment by ain** [comment]
Not a Ruby problem. 2.3.1 is installed properly. As I said, it's a `scss-lint` problem. Thanks nevertheless.

```
$ scss-lint _body.scss 
/Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fc5f5888e34 scss_lint-0.49.0> (NoMethodError)
	from /Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/ain/.rvm/gems/ruby-2.3.1/gems/scss_lint-0.49.0/bin/scss-lint:3:in `<top (required)>'
	from /Users/ain/.rvm/gems/ruby-2.3.1/bin/scss-lint:23:in `load'
	from /Users/ain/.rvm/gems/ruby-2.3.1/bin/scss-lint:23:in `<main>'
	from /Users/ain/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ain/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by lcd047** [comment]
Well, either way, it isn't something syntastic can work around.  There should be some better way for syntastic to detect crashes, or at least to figure out earlier what's going on, but there isn't.
